### ISSUE TITLE
qmlliveremote is missing

### ISSUE THREAD

**Issue by 3v1n0** [Pelagicore/qmllive#1]
In the docs and launcing `qmlliveruntime` is mentioned the tool `qmlliveremote`, but I don't see it building.

Has maybe it merged with `qmllivebench`? It seems that I can't add valid hosts there, BTW.

**Comment by jryannel** [comment]
Yes. Correct. We had initially a bench and a remote. The remote was the app to control a runtime. But now the bench can control the runtime. Ideally we would also skip the runtime in favour of a bench running headless.

**Comment by 3v1n0** [comment]
So, I guess you've to fix the docs.

However, I've been able to connect to my device, but I can't see the live preview of the device's content from the bench. I'm just getting errors (as it tries to load the qml files locally).
